"""migration

Revision ID: 6b509b596f50
Revises: c1288b53638b
Create Date: 2022-05-16 12:02:39.766487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b509b596f50'
down_revision = 'c1288b53638b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=200), nullable=False))
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
